spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: something
    password: something
    driver-class-name: org.postgres.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: eyJSb2xlIsisQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2Vyb
      expiration: 8640000 #one day
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account